# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:10.13-alpine
    environment:
      POSTGRES_DB: speleo_magazine
      POSTGRES_USER: speleo_magazine
      POSTGRES_PASSWORD: 12344321
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: